# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/e195728f-05a5-4e7b-90f3-7554c69155fc";
      fsType = "ext4";
      label  = "rootfs";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/E10F-1C35";
      fsType = "vfat";
    };

  fileSystems."/mnt/data1" =
    { device = "/dev/disk/by-uuid/e3dbd1fe-cddc-453a-8fa1-9f57c62e62e8"; # IronWolf 
      fsType = "xfs";
      options = [ "nofail" ];
    };
    
  fileSystems."/mnt/data2" =
    { device = "/dev/disk/by-uuid/afa4f2b4-52c9-4866-9613-3f087d3f199d"; # WD Red
      fsType = "xfs";
      options = [ "nofail" ];
    };
  
  fileSystems."/mnt/data3" =
    { device = "/dev/disk/by-uuid/3cfaa046-2350-4b4f-85a6-ef5200b2bf48"; # IronWolf 
      fsType = "xfs";
      options = [ "nofail" ];
    };
  
  # fileSystems."/mnt/parity" =
  #   { device = "/dev/disk/by-uuid/97a8b17d-ce51-4cc2-9ded-35a5e4dd7f8c"; # WD Red
  #     fsType = "xfs";
  #     options = [ "nofail" ];
  #   };

  fileSystems."/tmp/ramdisk" =
    { fsType = "tmpfs";
      options = [ "defaults" "size=16G" "x-gvfs-show" ];
    };
  
  fileSystems."/storage" = 
    { fsType = "fuse.mergerfs";
      device = "/mnt/data*";
      options = ["cache.files=partial" "dropcacheonclose=true" "category.create=mfs"];
    };



  swapDevices =
    [ { device = "/dev/disk/by-uuid/8fd47429-0a0e-4333-8900-4d5f34804800"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
